[package]
name = "dreamcore_image_processor"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.8"
imageproc = "0.25.0"
include_dir = "0.7.4"
rand = "0.9.2"
ab_glyph = "0.2.32"
rayon = "1.11.0"
derive-new = "0.7.0"
num-traits = "0.2.19"
strum_macros = "0.27.2"
strum = "0.27.2"
